import nodemailer from "nodemailer";
import cloudinary from "../../config/cloudinary.js";
import config from "../../config/env.js";
import contactRepository from "./contact.repository.js";

const contactService = {
  /**
   * Submit application to database and broadcast to administrator nodes
   * @param {Object} data - Form data
   * @param {Object} file - Buffer-based file object from Multer
   */
  async submitApplication(data, file) {
    // 1. Manual Cloudinary Upload from Buffer
    // Required since we switched to memoryStorage for nodemailer attachments
    const uploadToCloudinary = (fileBuffer) => {
      return new Promise((resolve, reject) => {
        const stream = cloudinary.uploader.upload_stream(
          { 
            folder: "resumes", 
            resource_type: "auto",
            public_id: `cv_${Date.now()}_${data.email.split('@')[0]}`
          },
          (error, result) => {
            if (error) reject(error);
            else resolve(result.secure_url);
          }
        );
        stream.end(fileBuffer);
      });
    };

    const resume_url = await uploadToCloudinary(file.buffer);

    // 2. Persist to MySQL Graph via Repository
    await contactRepository.createApplication({
      ...data,
      resume_url
    });

    // 3. Broadcast Formal Email with Binary Attachment
    const transporter = nodemailer.createTransport({
      host: config.mail.host,
      port: config.mail.port,
      secure: Number(config.mail.port) === 465, // Enforce strict numeric protocol check
      auth: {
        user: config.mail.user,
        pass: config.mail.pass,
      },
    });

    const mailOptions = {
      from: config.mail.from,
      to: config.mail.user, // Dynamically route to host node
      subject: `[CAREER_PROTOCOL] Application from ${data.first_name} ${data.last_name}`,
      html: `
        <div style="font-family: sans-serif; max-width: 600px; line-height: 1.6; border: 1px solid #f0f0f0; border-radius: 12px; padding: 24px;">
          <h2 style="color: #4f46e5; margin-top: 0;">Carrier Application Signal Captured</h2>
          <p><strong>Protocol Node:</strong> ${data.first_name} ${data.last_name}</p>
          <p><strong>Signal Source:</strong> ${data.email}</p>
          <p><strong>Assigned Sector/Campus:</strong> ${data.campus || 'Undisclosed'}</p>
          <p><strong>Archive Link:</strong> <a href="${resume_url}" style="color: #4f46e5; font-weight: bold;">View on Cloudinary</a></p>
          <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;" />
          <p style="font-size: 0.75rem; color: #999; text-transform: uppercase; letter-spacing: 1px;">Auto-generated by EDUVERSE Advanced Carrier Ingress</p>
        </div>
      `,
      attachments: [
        {
          filename: file.originalname,
          content: file.buffer,
        },
      ],
    };

    try {
      const info = await transporter.sendMail(mailOptions);
      return info;
    } catch (error) {
      console.error('Email Dispatch Failure:', error);
      // We still return success to the user as the application is saved in DB, 
      // but we should probably log this for manual intervention
      throw error; 
    }
  }
};

export default contactService;
